package com.ops.permissionmanager.core.model

/**
 * 全部可管理的 AppOps 操作目录。
 *
 * 提供按名称查找与枚举全部操作项的能力。
 */
object AppOpCatalog {

    private val catalog: List<AppOp> = listOf(
        AppOp("RUN_IN_BACKGROUND", "后台运行", OpGroup.BACKGROUND, isHighRisk = true),
        AppOp("RUN_ANY_IN_BACKGROUND", "任意后台运行", OpGroup.BACKGROUND, isHighRisk = true),
        AppOp("START_FOREGROUND", "启动前台服务", OpGroup.BACKGROUND),
        AppOp("FOREGROUND_SERVICE_TYPE", "前台服务类型", OpGroup.BACKGROUND),
        AppOp("FOREGROUND_SERVICE_SPECIAL_USE", "特殊用途前台服务", OpGroup.BACKGROUND),
        AppOp("SCHEDULE_EXACT_ALARM", "精确闹钟", OpGroup.BACKGROUND),
        AppOp("USE_ALARMS", "使用闹钟", OpGroup.BACKGROUND),
        AppOp("RUN_USER_INITIATED_JOBS", "用户发起后台任务", OpGroup.BACKGROUND),
        AppOp("INSTANT_APP_START_FOREGROUND", "即时应用启动前台", OpGroup.BACKGROUND),
        AppOp("AUTO_REVOKE_PERMISSIONS_IF_UNUSED", "自动撤销未用权限", OpGroup.BACKGROUND),
        AppOp("AUTO_REVOKE_MANAGED_BY_INSTALLER", "安装器管理自动撤销", OpGroup.BACKGROUND),

        AppOp("READ_CLIPBOARD", "读取剪贴板", OpGroup.PRIVACY, isHighRisk = true),
        AppOp("WRITE_CLIPBOARD", "写入剪贴板", OpGroup.PRIVACY, isHighRisk = true),
        AppOp("GET_USAGE_STATS", "读取应用使用情况", OpGroup.PRIVACY),
        AppOp("LOADER_USAGE_STATS", "加载使用统计", OpGroup.PRIVACY),
        AppOp("QUERY_ALL_PACKAGES", "查询所有应用", OpGroup.PRIVACY),
        AppOp("READ_DEVICE_IDENTIFIERS", "读取设备标识", OpGroup.PRIVACY, isHighRisk = true),
        AppOp("GET_ACCOUNTS", "获取账户", OpGroup.PRIVACY, isHighRisk = true),
        AppOp("MOCK_LOCATION", "模拟定位", OpGroup.PRIVACY, isHighRisk = true),
        AppOp("ACCESS_MEDIA_LOCATION", "访问媒体位置信息", OpGroup.PRIVACY),
        AppOp("READ_CELL_BROADCASTS", "读取小区广播", OpGroup.PRIVACY),
        AppOp("NEIGHBORING_CELLS", "读取邻近基站", OpGroup.PRIVACY),
        AppOp("SMS_FINANCIAL_TRANSACTIONS", "短信金融交易", OpGroup.PRIVACY),
        AppOp("READ_WRITE_HEALTH_DATA", "读写健康数据", OpGroup.PRIVACY),
        AppOp("READ_HEART_RATE", "读取心率", OpGroup.PRIVACY),
        AppOp("READ_SKIN_TEMPERATURE", "读取皮肤温度", OpGroup.PRIVACY),
        AppOp("READ_OXYGEN_SATURATION", "读取血氧饱和度", OpGroup.PRIVACY),
        AppOp("MANAGE_CREDENTIALS", "管理凭据", OpGroup.PRIVACY),
        AppOp("USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER", "使用 ICC 认证与设备标识", OpGroup.PRIVACY),
        AppOp("ACCESS_RESTRICTED_SETTINGS", "访问受限设置", OpGroup.PRIVACY),
        AppOp("READ_SYSTEM_GRAMMATICAL_GENDER", "读取系统语法性别", OpGroup.PRIVACY),
        AppOp("WRITE_SYSTEM_PREFERENCES", "写入系统偏好", OpGroup.PRIVACY),
        AppOp("RECEIVE_SENSITIVE_NOTIFICATIONS", "接收敏感通知", OpGroup.PRIVACY),
        AppOp("RAPID_CLEAR_NOTIFICATIONS_BY_LISTENER", "快速清除通知", OpGroup.PRIVACY),
        AppOp("READ_WIFI_STATE", "读取 WiFi 状态", OpGroup.PRIVACY),

        AppOp("FINE_LOCATION", "精确定位", OpGroup.LOCATION, isHighRisk = true),
        AppOp("COARSE_LOCATION", "粗略定位", OpGroup.LOCATION, isHighRisk = true),
        AppOp("GPS", "使用 GPS", OpGroup.LOCATION),
        AppOp("MONITOR_LOCATION", "持续定位", OpGroup.LOCATION, isHighRisk = true),
        AppOp("MONITOR_HIGH_POWER_LOCATION", "高功耗持续定位", OpGroup.LOCATION, isHighRisk = true),
        AppOp("FINE_LOCATION_SOURCE", "精确定位来源", OpGroup.LOCATION),
        AppOp("COARSE_LOCATION_SOURCE", "粗略定位来源", OpGroup.LOCATION),
        AppOp("EMERGENCY_LOCATION", "紧急定位", OpGroup.LOCATION),
        AppOp("UWB_RANGING", "超宽带测距", OpGroup.LOCATION),
        AppOp("RANGING", "测距", OpGroup.LOCATION),
        AppOp("NEARBY_WIFI_DEVICES", "附近 WiFi 设备", OpGroup.LOCATION),
        AppOp("WIFI_SCAN", "WiFi 扫描", OpGroup.LOCATION),
        AppOp("ACTIVITY_RECOGNITION", "活动识别", OpGroup.LOCATION),
        AppOp("ACTIVITY_RECOGNITION_SOURCE", "活动识别来源", OpGroup.LOCATION),

        AppOp("READ_CONTACTS", "读取联系人", OpGroup.CONTACTS),
        AppOp("WRITE_CONTACTS", "写入联系人", OpGroup.CONTACTS),
        AppOp("READ_CALENDAR", "读取日历", OpGroup.CONTACTS),
        AppOp("WRITE_CALENDAR", "写入日历", OpGroup.CONTACTS),

        AppOp("READ_PHONE_STATE", "读取手机状态", OpGroup.PHONE),
        AppOp("READ_PHONE_NUMBERS", "读取手机号码", OpGroup.PHONE),
        AppOp("READ_CALL_LOG", "读取通话记录", OpGroup.PHONE, isHighRisk = true),
        AppOp("WRITE_CALL_LOG", "写入通话记录", OpGroup.PHONE, isHighRisk = true),
        AppOp("CALL_PHONE", "拨打电话", OpGroup.PHONE),
        AppOp("ANSWER_PHONE_CALLS", "接听电话", OpGroup.PHONE),
        AppOp("PROCESS_OUTGOING_CALLS", "处理拨出电话", OpGroup.PHONE),
        AppOp("ADD_VOICEMAIL", "添加语音邮件", OpGroup.PHONE),
        AppOp("USE_SIP", "使用 SIP", OpGroup.PHONE),
        AppOp("MANAGE_ONGOING_CALLS", "管理进行中通话", OpGroup.PHONE),
        AppOp("PHONE_CALL_MICROPHONE", "通话麦克风", OpGroup.PHONE),
        AppOp("PHONE_CALL_CAMERA", "通话相机", OpGroup.PHONE),
        AppOp("RECORD_INCOMING_PHONE_AUDIO", "录制来电音频", OpGroup.PHONE),
        AppOp("ACCEPT_HANDOVER", "接受通话切换", OpGroup.PHONE),

        AppOp("READ_SMS", "读取短信", OpGroup.SMS, isHighRisk = true),
        AppOp("WRITE_SMS", "写入短信", OpGroup.SMS, isHighRisk = true),
        AppOp("RECEIVE_SMS", "接收短信", OpGroup.SMS, isHighRisk = true),
        AppOp("RECEIVE_EMERGENCY_SMS", "接收紧急短信", OpGroup.SMS),
        AppOp("RECEIVE_EMERGENCY_BROADCAST", "接收紧急广播", OpGroup.SMS),
        AppOp("RECEIVE_MMS", "接收彩信", OpGroup.SMS, isHighRisk = true),
        AppOp("RECEIVE_WAP_PUSH", "接收 WAP 推送", OpGroup.SMS),
        AppOp("SEND_SMS", "发送短信", OpGroup.SMS, isHighRisk = true),
        AppOp("READ_ICC_SMS", "读取 SIM 短信", OpGroup.SMS),
        AppOp("WRITE_ICC_SMS", "写入 SIM 短信", OpGroup.SMS),

        AppOp("READ_MEDIA_IMAGES", "读取图片", OpGroup.MEDIA, isHighRisk = true),
        AppOp("WRITE_MEDIA_IMAGES", "写入图片", OpGroup.MEDIA, isHighRisk = true),
        AppOp("READ_MEDIA_VIDEO", "读取视频", OpGroup.MEDIA, isHighRisk = true),
        AppOp("WRITE_MEDIA_VIDEO", "写入视频", OpGroup.MEDIA, isHighRisk = true),
        AppOp("READ_MEDIA_AUDIO", "读取音频", OpGroup.MEDIA, isHighRisk = true),
        AppOp("WRITE_MEDIA_AUDIO", "写入音频", OpGroup.MEDIA, isHighRisk = true),
        AppOp("READ_MEDIA_VISUAL_USER_SELECTED", "读取用户选择的媒体", OpGroup.MEDIA),
        AppOp("MANAGE_MEDIA", "管理媒体", OpGroup.MEDIA),
        AppOp("PROJECT_MEDIA", "投屏媒体", OpGroup.MEDIA),
        AppOp("MEDIA_ROUTING_CONTROL", "媒体路由控制", OpGroup.MEDIA),
        AppOp("TAKE_MEDIA_BUTTONS", "媒体按键", OpGroup.MEDIA),
        AppOp("TAKE_AUDIO_FOCUS", "音频焦点", OpGroup.MEDIA),
        AppOp("PLAY_AUDIO", "播放音频", OpGroup.MEDIA),
        AppOp("CONTROL_AUDIO", "控制音频", OpGroup.MEDIA),
        AppOp("CONTROL_AUDIO_PARTIAL", "部分控制音频", OpGroup.MEDIA),

        AppOp("RECORD_AUDIO", "录音", OpGroup.AUDIO, isHighRisk = true),
        AppOp("RECORD_AUDIO_HOTWORD", "唤醒词录音", OpGroup.AUDIO),
        AppOp("RECORD_AUDIO_OUTPUT", "录制音频输出", OpGroup.AUDIO),
        AppOp("RECORD_AUDIO_SANDBOXED", "沙盒录音", OpGroup.AUDIO),
        AppOp("RECEIVE_AMBIENT_TRIGGER_AUDIO", "接收环境触发音频", OpGroup.AUDIO),
        AppOp("RECEIVE_SOUNDTRIGGER_AUDIO", "接收声音触发音频", OpGroup.AUDIO),
        AppOp("RECEIVE_EXPLICIT_USER_INTERACTION_AUDIO", "接收用户交互音频", OpGroup.AUDIO),
        AppOp("RECEIVE_SANDBOX_TRIGGER_AUDIO", "接收沙盒触发音频", OpGroup.AUDIO),
        AppOp("MUTE_MICROPHONE", "静音麦克风", OpGroup.AUDIO, isHighRisk = true),
        AppOp("AUDIO_VOICE_VOLUME", "通话音量", OpGroup.AUDIO),
        AppOp("AUDIO_RING_VOLUME", "铃声音量", OpGroup.AUDIO),
        AppOp("AUDIO_MEDIA_VOLUME", "媒体音量", OpGroup.AUDIO),
        AppOp("AUDIO_ALARM_VOLUME", "闹钟音量", OpGroup.AUDIO),
        AppOp("AUDIO_NOTIFICATION_VOLUME", "通知音量", OpGroup.AUDIO),
        AppOp("AUDIO_BLUETOOTH_VOLUME", "蓝牙音量", OpGroup.AUDIO),
        AppOp("AUDIO_MASTER_VOLUME", "主音量", OpGroup.AUDIO),
        AppOp("AUDIO_ACCESSIBILITY_VOLUME", "无障碍音量", OpGroup.AUDIO),

        AppOp("POST_NOTIFICATION", "发送通知", OpGroup.NOTIFICATION),
        AppOp("READ_NOTIFICATIONS", "读取通知", OpGroup.NOTIFICATION, isHighRisk = true),
        AppOp("ACCESS_NOTIFICATIONS", "访问通知", OpGroup.NOTIFICATION, isHighRisk = true),
        AppOp("USE_FULL_SCREEN_INTENT", "全屏通知", OpGroup.NOTIFICATION),
        AppOp("SYSTEM_EXEMPT_FROM_DISMISSIBLE_NOTIFICATIONS", "免于通知折叠", OpGroup.NOTIFICATION),

        AppOp("CAMERA", "相机", OpGroup.SENSOR, isHighRisk = true),
        AppOp("CAMERA_SANDBOXED", "沙盒相机", OpGroup.SENSOR),
        AppOp("VIBRATE", "振动", OpGroup.SENSOR),
        AppOp("BODY_SENSORS", "身体传感器", OpGroup.SENSOR, isHighRisk = true),
        AppOp("USE_FINGERPRINT", "使用指纹", OpGroup.SENSOR),
        AppOp("USE_BIOMETRIC", "使用生物识别", OpGroup.SENSOR, isHighRisk = true),

        AppOp("WAKE_LOCK", "唤醒锁", OpGroup.BATTERY),
        AppOp("KEEP_SCREEN_ON", "保持屏幕常亮", OpGroup.BATTERY),
        AppOp("TURN_SCREEN_ON", "点亮屏幕", OpGroup.BATTERY),
        AppOp("RUN_IN_BACKGROUND_WHITELIST", "后台运行白名单", OpGroup.BATTERY),
        AppOp("CHANGE_WIFI_STATE", "修改 WiFi 状态", OpGroup.BATTERY),
        AppOp("CHANGE_NETWORK_STATE", "修改网络状态", OpGroup.BATTERY),
        AppOp("ENABLE_MOBILE_DATA_BY_USER", "用户启用移动数据", OpGroup.BATTERY),
        AppOp("SYSTEM_EXEMPT_FROM_POWER_RESTRICTIONS", "免于电量限制", OpGroup.BATTERY),
        AppOp("SYSTEM_EXEMPT_FROM_HIBERNATION", "免于休眠", OpGroup.BATTERY),
        AppOp("SYSTEM_EXEMPT_FROM_SUSPENSION", "免于挂起", OpGroup.BATTERY),
        AppOp("SYSTEM_EXEMPT_FROM_ACTIVITY_BG_START_RESTRICTION", "免于后台启动限制", OpGroup.BATTERY),

        AppOp("READ_EXTERNAL_STORAGE", "读取外部存储", OpGroup.STORAGE, isHighRisk = true),
        AppOp("WRITE_EXTERNAL_STORAGE", "写入外部存储", OpGroup.STORAGE, isHighRisk = true),
        AppOp("LEGACY_STORAGE", "传统存储模式", OpGroup.STORAGE),
        AppOp("NO_ISOLATED_STORAGE", "非隔离存储", OpGroup.STORAGE),
        AppOp("MANAGE_EXTERNAL_STORAGE", "管理所有文件", OpGroup.STORAGE, isHighRisk = true),
        AppOp("ARCHIVE_ICON_OVERLAY", "归档图标", OpGroup.STORAGE),
        AppOp("UNARCHIVAL_CONFIRMATION", "取消归档确认", OpGroup.STORAGE),

        AppOp("BLUETOOTH_SCAN", "蓝牙扫描", OpGroup.BLUETOOTH, isHighRisk = true),
        AppOp("BLUETOOTH_CONNECT", "蓝牙连接", OpGroup.BLUETOOTH),
        AppOp("BLUETOOTH_ADVERTISE", "蓝牙广播", OpGroup.BLUETOOTH),

        AppOp("SYSTEM_ALERT_WINDOW", "悬浮窗", OpGroup.SYSTEM, isHighRisk = true),
        AppOp("WRITE_SETTINGS", "修改系统设置", OpGroup.SYSTEM, isHighRisk = true),
        AppOp("REQUEST_INSTALL_PACKAGES", "安装未知应用", OpGroup.SYSTEM),
        AppOp("REQUEST_DELETE_PACKAGES", "请求删除应用", OpGroup.SYSTEM),
        AppOp("PICTURE_IN_PICTURE", "画中画", OpGroup.SYSTEM),
        AppOp("WRITE_WALLPAPER", "修改壁纸", OpGroup.SYSTEM),
        AppOp("TOAST_WINDOW", "弹窗", OpGroup.SYSTEM),
        AppOp("ASSIST_STRUCTURE", "辅助结构", OpGroup.SYSTEM),
        AppOp("ASSIST_SCREENSHOT", "辅助截图", OpGroup.SYSTEM),
        AppOp("ACTIVATE_VPN", "激活 VPN", OpGroup.SYSTEM, isHighRisk = true),
        AppOp("ACTIVATE_PLATFORM_VPN", "激活平台 VPN", OpGroup.SYSTEM),
        AppOp("ESTABLISH_VPN_SERVICE", "建立 VPN 服务", OpGroup.SYSTEM, isHighRisk = true),
        AppOp("ESTABLISH_VPN_MANAGER", "建立 VPN 管理", OpGroup.SYSTEM),
        AppOp("MANAGE_IPSEC_TUNNELS", "管理 IPsec 隧道", OpGroup.SYSTEM),
        AppOp("BIND_ACCESSIBILITY_SERVICE", "绑定无障碍服务", OpGroup.SYSTEM, isHighRisk = true),
        AppOp("ACCESS_ACCESSIBILITY", "访问无障碍", OpGroup.SYSTEM, isHighRisk = true),
        AppOp("CREATE_ACCESSIBILITY_OVERLAY", "创建无障碍悬浮层", OpGroup.SYSTEM),
        AppOp("INTERACT_ACROSS_PROFILES", "跨用户资料交互", OpGroup.SYSTEM),
        AppOp("INTERACT_ACROSS_USERS", "跨用户交互", OpGroup.SYSTEM),
        AppOp("CAPTURE_CONSENTLESS_BUGREPORT_ON_USERDEBUG_BUILD", "无同意捕获错误报告", OpGroup.SYSTEM),

        AppOp("OP_RESERVED_FOR_TESTING", "保留测试操作", OpGroup.OTHER)
    )

    private val byName: Map<String, AppOp> = catalog.associateBy { it.name }

    /**
     * 根据操作名查找，未找到返回 [null]。
     */
    fun find(name: String): AppOp? = byName[name]

    /**
     * 返回全部操作项。
     */
    fun all(): List<AppOp> = catalog
}