package com.ops.permissionmanager.core.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * 底部 Tab 专用图标：从 material-icons-extended 1.7.8 提取字节码重建的自建 ImageVector。
 * 仅用到 Apps / Tune / History 三个（均不在 material-icons-core），
 * 其余图标（Search/Settings/ArrowBack/KeyboardArrowRight/Done）全部走 material-icons-core，
 * 从而整个工程可移除全量 material-icons-extended 库（大幅减 APK/DEX 体积）。
 */
object TabIcons {

    val History: ImageVector = ImageVector.Builder("History", 24.dp, 24.dp, 24f, 24f).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(13f, 3f)
            curveToRelative(-4.97f, 0f, -9f, 4.03f, -9f, 9f)
            lineTo(1f, 12f)
            lineToRelative(3.89f, 3.89f)
            lineToRelative(0.07f, 0.14f)
            lineTo(9f, 12f)
            lineTo(6f, 12f)
            curveToRelative(0f, -3.87f, 3.13f, -7f, 7f, -7f)
            reflectiveCurveToRelative(7f, 3.13f, 7f, 7f)
            reflectiveCurveToRelative(-3.13f, 7f, -7f, 7f)
            curveToRelative(-1.93f, 0f, -3.68f, -0.79f, -4.94f, -2.06f)
            lineToRelative(-1.42f, 1.42f)
            curveTo(8.27f, 19.99f, 10.51f, 21f, 13f, 21f)
            curveToRelative(4.97f, 0f, 9f, -4.03f, 9f, -9f)
            reflectiveCurveToRelative(-4.03f, -9f, -9f, -9f)
            close()
            moveTo(12f, 8f)
            verticalLineToRelative(5f)
            lineToRelative(4.28f, 2.54f)
            lineToRelative(0.72f, -1.21f)
            lineToRelative(-3.5f, -2.08f)
            lineTo(13.5f, 8f)
            lineTo(12f, 8f)
            close()
        }
    }.build()

    val Tune: ImageVector = ImageVector.Builder("Tune", 24.dp, 24.dp, 24f, 24f).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(3f, 17f)
            verticalLineToRelative(2f)
            horizontalLineToRelative(6f)
            verticalLineToRelative(-2f)
            lineTo(3f, 17f)
            close()
            moveTo(3f, 5f)
            verticalLineToRelative(2f)
            horizontalLineToRelative(10f)
            lineTo(13f, 5f)
            lineTo(3f, 5f)
            close()
            moveTo(13f, 21f)
            verticalLineToRelative(-2f)
            horizontalLineToRelative(8f)
            verticalLineToRelative(-2f)
            horizontalLineToRelative(-8f)
            verticalLineToRelative(-2f)
            horizontalLineToRelative(-2f)
            verticalLineToRelative(6f)
            horizontalLineToRelative(2f)
            close()
            moveTo(7f, 9f)
            verticalLineToRelative(2f)
            lineTo(3f, 11f)
            verticalLineToRelative(2f)
            horizontalLineToRelative(4f)
            verticalLineToRelative(2f)
            horizontalLineToRelative(2f)
            lineTo(9f, 9f)
            lineTo(7f, 9f)
            close()
            moveTo(21f, 13f)
            verticalLineToRelative(-2f)
            lineTo(11f, 11f)
            verticalLineToRelative(2f)
            horizontalLineToRelative(10f)
            close()
            moveTo(15f, 9f)
            horizontalLineToRelative(2f)
            lineTo(17f, 7f)
            horizontalLineToRelative(4f)
            lineTo(21f, 5f)
            horizontalLineToRelative(-4f)
            lineTo(17f, 3f)
            horizontalLineToRelative(-2f)
            verticalLineToRelative(6f)
            close()
        }
    }.build()

    val Apps: ImageVector = ImageVector.Builder("Apps", 24.dp, 24.dp, 24f, 24f).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(4f, 8f)
            horizontalLineToRelative(4f)
            lineTo(8f, 4f)
            lineTo(4f, 4f)
            verticalLineToRelative(4f)
            close()
            moveTo(10f, 20f)
            horizontalLineToRelative(4f)
            verticalLineToRelative(-4f)
            horizontalLineToRelative(-4f)
            verticalLineToRelative(4f)
            close()
            moveTo(4f, 20f)
            horizontalLineToRelative(4f)
            verticalLineToRelative(-4f)
            lineTo(4f, 16f)
            verticalLineToRelative(4f)
            close()
            moveTo(4f, 14f)
            horizontalLineToRelative(4f)
            verticalLineToRelative(-4f)
            lineTo(4f, 10f)
            verticalLineToRelative(4f)
            close()
            moveTo(10f, 14f)
            horizontalLineToRelative(4f)
            verticalLineToRelative(-4f)
            horizontalLineToRelative(-4f)
            verticalLineToRelative(4f)
            close()
            moveTo(16f, 4f)
            verticalLineToRelative(4f)
            horizontalLineToRelative(4f)
            lineTo(20f, 4f)
            horizontalLineToRelative(-4f)
            close()
            moveTo(10f, 8f)
            horizontalLineToRelative(4f)
            lineTo(14f, 4f)
            horizontalLineToRelative(-4f)
            verticalLineToRelative(4f)
            close()
            moveTo(16f, 14f)
            horizontalLineToRelative(4f)
            verticalLineToRelative(-4f)
            horizontalLineToRelative(-4f)
            verticalLineToRelative(4f)
            close()
            moveTo(16f, 20f)
            horizontalLineToRelative(4f)
            verticalLineToRelative(-4f)
            horizontalLineToRelative(-4f)
            verticalLineToRelative(4f)
            close()
        }
    }.build()

}
